id: project-control-center
name: Project Control Center
type: long_term
stage: building
status: active
priority: 1
tags:
  - meta
  - bootstrap
success_criteria: |
  Able to fully manage 10-100 projects effectively.
  Projects can self-determine and self-attain their own success.
  System learns from failures and doesn't repeat mistakes.
success_metrics:
  - name: Active projects managed
    target: 10
    current: 1
  - name: Run success rate (rolling)
    target: 80%
    current: 63%
    notes: "12/19 recent terminal runs - trending up from 36% historical"

